@startuml
autonumber
actor "Client" as CLI

activate CLI
CLI -> ":System" : Starts the process of performing an Order
activate ":System"
":System" --> CLI : Presents a list of products that are available
deactivate ":System"

CLI -> ":System" : Chooses the product(s)
activate ":System"
":System" --> CLI : Displays the list of products and the total price, asking the Client to confirm it
deactivate ":System"

CLI -> ":System" : Confirms the data and does the automatic payment
activate ":System"
":System" --> CLI : Shows an invoice and informs the Client about the success of the operation.
deactivate ":System"

deactivate CLI
@enduml
