@startuml
autonumber
actor "Administrator" as ADM

activate ADM
ADM -> ":System" : Starts the process add drone
activate ":System"
":System" --> ADM : Asks the Administrator for the Pharmacy that he wants add a drone
deactivate ":System"

ADM -> ":System" : Selects the Pharmacy he wants add a drone.
activate ":System"
":System" --> ADM : Asks for the necessary drone's data (i.e. capacity (KG), power (W), max battery (W/H))
deactivate ":System"

ADM -> ":System" : Enters the requested data.
activate ":System"
":System" --> ADM : Displays the data, asking him to confirm it
deactivate ":System"

ADM -> ":System" :  Confirms
activate ":System"
":System" --> ADM :  Informs about the success of the operation
deactivate ":System"

deactivate ADM

@enduml
