@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":AddCourierUI" as UI
participant ":AddCourierController" as CTRL
participant ":PharmacyDB" as PHARDB
participant ":Courier" as SCOOTER
participant "phar\n:Pharmacy" as PHAR
participant "courier\n:Courier" as OSCOOTER
participant ":CourierDB" as SCOOTERDB
participant "pharmaciesList\n:List<Pharmacy>" as LPHAR

activate ADM
ADM -> UI : Starts the process of adding a courier
activate UI

UI -> CTRL : pharmaciesList = getPharmaciesList()
activate CTRL

CTRL -> PHARDB: pharmaciesList = getAllPharmacies()
activate PHARDB
deactivate PHARDB

deactivate CTRL

UI --> ADM : Shows to the Administrator a list of pharmacies and asks him to \n choose the one he wants add a courier to
deactivate UI

ADM -> UI : Selects the Pharmacy
activate UI

UI -> CTRL : getPharmacyByEmail(PharmacyEmail)
activate CTRL

CTRL -> PHARDB: phar = getPharmacy(PharmacyEmail)
activate PHARDB
deactivate PHARDB

deactivate CTRL

UI --> ADM : Asks for the necessary data that characterizes the courier (name, \n email, phone number, social security number, nif)
deactivate UI

ADM -> UI : Enters the requested data
activate UI

UI -> CTRL : newCourier(nif,name,email,phoneNumber,socialSecurityNumber,pwd)
activate CTRL

CTRL -> SCOOTER: courier = newCourier(nif,name,email,phoneNumber,socialSecurityNumber,pwd)
activate SCOOTER
deactivate SCOOTER

UI --> ADM:  Displays the data, asking the Administrator to confirm it
deactivate CTRL
deactivate UI

ADM -> UI : Confirms
activate UI
UI -> CTRL : addCourier()
activate CTRL

CTRL -> PHAR : pharEmail = getEmail()
activate PHAR
deactivate PHAR

CTRL -> OSCOOTER : save(pharEmail)
activate OSCOOTER

OSCOOTER -> SCOOTERDB : addCourier(courier,pharEmail)
activate SCOOTERDB
deactivate SCOOTERDB
deactivate OSCOOTER

UI --> ADM : Informs the Administrator about the success of the operation
deactivate CTRL
deactivate UI

deactivate ADM

@enduml
